CREATE TABLE IF NOT EXISTS add_invoice (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Invoice_Name VARCHAR(255) NOT NULL,
   
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)