CREATE TABLE IF NOT EXISTS daily_expense (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    
    Expense_Id VARCHAR(255) NOT NULL UNIQUE,
   
    Date DATE NOT NULL,
    Purpose VARCHAR(255) NOT NULL,
    Amount DECIMAL(10,2)  NOT NULL,
    Payment_Method ENUM('Cash', 'Cheque', 'Online') DEFAULT 'Cash',
    Paid_Via VARCHAR(255) DEFAULT NULL,


    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);