CREATE TABLE IF NOT EXISTS financial_year (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Financial_Year VARCHAR(255) NOT NULL UNIQUE,
    Start_Date DATE NOT NULL,
    End_Date DATE NOT NULL,
    Current_Financial_Year BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)